// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_mebT_umJ-AdqFDOOkbj-LrKgqD2N9A',
    appId: '1:285072757085:web:d6ef58a963ab2ed9b7d8b4',
    messagingSenderId: '285072757085',
    projectId: 'fir-test-16fb9',
    authDomain: 'fir-test-16fb9.firebaseapp.com',
    storageBucket: 'fir-test-16fb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkQyLTkjm8wdBxWA_goIIAT4JXyINKqc',
    appId: '1:285072757085:android:0b74dda0e8d994ebb7d8b4',
    messagingSenderId: '285072757085',
    projectId: 'fir-test-16fb9',
    storageBucket: 'fir-test-16fb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq_uTjxzGJPPBeT612REZczOUM8exmB8A',
    appId: '1:285072757085:ios:d850081500fccf68b7d8b4',
    messagingSenderId: '285072757085',
    projectId: 'fir-test-16fb9',
    storageBucket: 'fir-test-16fb9.appspot.com',
    iosClientId: '285072757085-cdhrq4kbvc7vgqtc4hc2kidugu453cuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq_uTjxzGJPPBeT612REZczOUM8exmB8A',
    appId: '1:285072757085:ios:8751e842bad6ca03b7d8b4',
    messagingSenderId: '285072757085',
    projectId: 'fir-test-16fb9',
    storageBucket: 'fir-test-16fb9.appspot.com',
    iosClientId: '285072757085-1mln9g8ru6l62q6l2j9cendfqegnh4tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
